baseURL = "https://hunde.isabellmartins.de"
defaultContentLanguage = "de"
disableKinds = ["taxonomy", "term", "RSS"]
enableRobotsTXT = true
languageCode = "de"
theme = "roxo-hugo"
themesDir = "../themes"
title = "Isabell Martins - ErnÃ¤hrungsberatung fÃ¼r Hunde"
[[menu.nav]]
name = "Leistungen & Preise"
weight = 2
[[menu.nav]]
name = "Termin vereinbaren"
url = "contact"
weight = 4
[[menu.nav]]
name = "ğŸ‘·ğŸ»â€â™€ï¸ Weitere Inhalte folgen in KÃ¼rze"
weight = 1
[params]
author = "Isabell Martins"
dateFormat = "26 FEB 1994"
description = "ErnÃ¤hrungsberatung fÃ¼r Hunde - Professionell & unabhÃ¤ngig"
favicon = "images/favicon.png"
images = ["images/share-image.png"]
logo = "images/logo.png"
title = "Isabell Martins - ErnÃ¤hrungsberatung fÃ¼r Hunde"
[params.navAction]
name = "Termin vereinbaren"
status = true
url = "contact"
